version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - graphviz
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      - git fetch --shallow-since=2022-10-01 || true
    pre_install:
      - git update-index --assume-unchanged docs/conf.py

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all

formats: []
