comment: off
codecov:
  branch: main
coverage:
  status:
    project:
      default:
        target: auto
        # this allows a small drop from the previous base commit coverage
        threshold: 0.05%
