version: 2

jobs:
  build:
    docker:
      - image: quay.io/pypa/manylinux1_i686
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: /opt/python/cp36-cp36m/bin/pip install numpy scipy astropy pytest-astropy pytest-xdist Cython jinja2
      - run:
          name: Run tests
          command: PYTHONHASHSEED=42 /opt/python/cp36-cp36m/bin/python setup.py test --parallel=4
